// importe o arquivo que deseja testar e depois execute o comando "yarn dev" no terminal
// import './creational/prototype/prototype-deepcopy';
// import './creational/factory-method';
// import './creational/abstract-factory';
// import './structural/composite/validation-composite';
// import './structural/adapter';
// import './structural/bridge';
// import './structural/decorator';
// import './structural/facade';
// import './structural/proxy';
// import './structural/flyweight';
// import './behavioral/strategy';
// import './behavioral/command';
// import './behavioral/memento';
// import './behavioral/state';
// import './behavioral/mediator';
// import './behavioral/chain-of-responsability';
// import './behavioral/template-method';
// import './behavioral/iterator';
import './behavioral/visitor';
